### ISSUE TITLE
`View#append` fails unless the parent view has sufficient attributes

### ISSUE THREAD

**Issue by hby** [pakyow/pakyow#102]
Get a pakyow project set up and go in console.
```
$ bundle exec pakyow console
irb(main):001:0> view = Pakyow::Presenter::View.new('<div></div>')
=> #<Pakyow::Presenter::View:0x007fd33fc8a3d8 @doc=#<Pakyow::Presenter::StringDoc:0x007fd33fc8a180 @structure=[["<div></div>", {}, []]]>>
irb(main):002:0> view.append(Pakyow::Presenter::View.new('<div></div>'))
NoMethodError: undefined method `[]' for nil:NilClass
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/pakyow-presenter/lib/presenter/string_doc.rb:248:in `children'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/pakyow-presenter/lib/presenter/string_doc.rb:100:in `append'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/pakyow-presenter/lib/presenter/view.rb:84:in `append'
    from (irb):2
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/lib/commands/console.rb:16:in `<top (required)>'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/bin/pakyow:15:in `require'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pakyow-b3d87b2d9ad6/bin/pakyow:15:in `<top (required)>'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/pakyow:23:in `load'
    from /Users/hby/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/pakyow:23:in `<main>’
```

If you add, say, some `data-prop` to the parent view, it's fine. Not just any attribute will do, though.

```
irb(main):005:0> view = Pakyow::Presenter::View.new('<div data-prop="dummy"></div>')
=> #<Pakyow::Presenter::View:0x007fd33fc317b0 @doc=#<Pakyow::Presenter::StringDoc:0x007fd33fc313c8 @structure=[["<div ", {:"data-prop"=>"dummy"}, [[">", {}, []], ["</div>", {}, []]]]]>>
irb(main):006:0> view.append(Pakyow::Presenter::View.new('<div></div>'))
=> [["<div></div>", {}, []]]
```

**Comment by bryanp** [comment]
I've looked into this some and appending to an insignificant node is currently unsupported. The reason is that in typical usage of Pakyow, a developer is only interacting with significant nodes (e.g. scopes and props). For efficiency, insignificant nodes aren't parsed in a way they can be changed.

I am hesitant about making every node significant because of the performance implications. Perhaps a middle ground would be to make the root node significant, no matter what.

@hby Interested in your opinion here.

**Comment by bryanp** [comment]
Here's a commit that makes root nodes appendable, but not fully significant: https://github.com/pakyow/pakyow/commit/39abc41dc15410eabc1b797077c8dbf8b584cdd6

The difference is the attributes cannot be changed on a root node, unless it's significant.
