### ISSUE TITLE
Ruby 2.7

### ISSUE THREAD

**Issue by waghanza** [pakyow/pakyow#482]
Hi,

Does `pakyow` support `ruby` **2.7** ?

With the implementation in https://github.com/the-benchmarker/web-frameworks/pull/3003, I have
 ```
severity=unknown timestamp="2020-06-20 13:17:09 +0000" id=565ecdec type=pkyw elapsed=50.02ms message="\e[34;1mPakyow \u203A Production \u203A http://0.0.0.0:3000\e[0m\e[3m\nUse Ctrl-C to shut down the environment.\e[0m"
/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:42: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/share/gems/gems/process-group-1.2.3/lib/process/group.rb:168: warning: The called method `fork' is defined here
severity=errorseverity =timestamperror="2020-06-20 13:17:09 +0000"  timestampid=="2020-06-20 13:17:09 +0000"565ecdec id =565ecdectype type==pkywpkyw elapsed =54.23mselapsed =exception=54.03msRuntimeError  messageexception="Pakyow will not boot without a secret configured in `Pakyow.config.secrets`"=RuntimeError backtrace ="/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/verifier.rb:24:in `block (2 levels) in <module:Verifier>',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `instance_exec',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `block in call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `each',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:135:in `performing',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/environment.rb:251:in `boot',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/processes/server.rb:27:in `run',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/running.rb:56:in `block (3 levels) in <module:Running>',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:44:in `block (4 levels) in run_process',/usr/share/gems/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'"message
="Pakyow will not boot without a secret configured in `Pakyow.config.secrets`" backtrace="/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/verifier.rb:24:in `block (2 levels) in <module:Verifier>',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `instance_exec',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `block in call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `each',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:135:in `performing',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/environment.rb:251:in `boot',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/processes/server.rb:27:in `run',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/running.rb:56:in `block (3 levels) in <module:Running>',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:44:in `block (4 levels) in run_process',/usr/share/gems/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'"
severity=error timestamp="2020-06-20 13:17:09 +0000" id=565ecdec type=pkyw elapsed=55.71ms exception=RuntimeError message="Pakyow will not boot without a secret configured in `Pakyow.config.secrets`" backtrace="/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/verifier.rb:24:in `block (2 levels) in <module:Verifier>',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `instance_exec',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `block in call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `each',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:135:in `performing',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/environment.rb:251:in `boot',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/processes/server.rb:27:in `run',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/running.rb:56:in `block (3 levels) in <module:Running>',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:44:in `block (4 levels) in run_process',/usr/share/gems/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'"
severity=error timestamp="2020-06-20 13:17:09 +0000" id=565ecdec type=pkyw elapsed=57.38ms exception=RuntimeError message="Pakyow will not boot without a secret configured in `Pakyow.config.secrets`" backtrace="/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/verifier.rb:24:in `block (2 levels) in <module:Verifier>',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `instance_exec',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `block in call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `each',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:135:in `performing',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/environment.rb:251:in `boot',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/processes/server.rb:27:in `run',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/running.rb:56:in `block (3 levels) in <module:Running>',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:44:in `block (4 levels) in run_process',/usr/share/gems/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'"
severity=error timestamp="2020-06-20 13:17:09 +0000" id=565ecdec type=pkyw elapsed=60.10ms exception=RuntimeError message="Pakyow will not boot without a secret configured in `Pakyow.config.secrets`" backtrace="/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/verifier.rb:24:in `block (2 levels) in <module:Verifier>',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `instance_exec',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:149:in `block in call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `each',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:147:in `call_hooks',/usr/share/gems/gems/pakyow-support-1.0.5/lib/pakyow/support/hookable.rb:135:in `performing',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/environment.rb:251:in `boot',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/processes/server.rb:27:in `run',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/behavior/running.rb:56:in `block (3 levels) in <module:Running>',/usr/share/gems/gems/pakyow-core-1.0.5/lib/pakyow/process_manager.rb:44:in `block (4 levels) in run_process',/usr/share/gems/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'"

severity=unknown timestamp="2020-06-20 13:17:09 +0000" id=565ecdec type=pkyw elapsed=94.64ms message=Goodbye
```

Regards,

PS : I have the same message on **2.6**

**Comment by bryanp** [comment]
Apologies for the delay, I missed a notification. Pakyow supports Ruby 2.7 yes. The issue you're encountering is that Pakyow will fail to boot if a secret is not configured in production. This prevents you from accidentally deploying an insecure project. You can solve this issue by configuring a secret on the environment. 

The easiest way to configure a secret is to set the `SECRET` environment variable. Pakyow automatically configures secrets [uses the `SECRET` environment variable in production](https://github.com/pakyow/pakyow/blob/bdbdf36b5b222c775449044d4e01810cd6cd0452/pakyow-core/lib/pakyow/config.rb#L44-L46). Another way is to set it directly in `config/environment.rb`:

```ruby
Pakyow.configure :production do
  config.secrets = ["my-secret"]
end
```

**Comment by waghanza** [comment]
Ok.
