### ISSUE TITLE
Pakyow not working with Ruby 3.0.1? "tried to create Proc object without a block (ArgumentError)"

### ISSUE THREAD

**Issue by bolandross** [pakyow/pakyow#568]
Any ideas why this is happening?

```
bolandross@MacBook-12 Downloads % pakyow create helloworld
/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-support-1.0.1/lib/pakyow/support/pipeline.rb:190:in `new': tried to create Proc object without a block (ArgumentError)
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-support-1.0.1/lib/pakyow/support/pipeline.rb:190:in `initialize'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-support-1.0.1/lib/pakyow/support/pipeline.rb:128:in `new'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-support-1.0.1/lib/pakyow/support/pipeline.rb:128:in `pipeline'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-support-1.0.1/lib/pakyow/support/pipeline.rb:91:in `included'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/operation.rb:17:in `include'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/operation.rb:17:in `<class:Operation>'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/operation.rb:11:in `<module:Pakyow>'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/operation.rb:10:in `<top (required)>'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/application/behavior/operations.rb:5:in `<top (required)>'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/application.rb:23:in `<top (required)>'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/environment.rb:34:in `<top (required)>'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/lib/pakyow/cli.rb:9:in `<top (required)>'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/bolandross/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pakyow-core-1.0.1/commands/pakyow:11:in `<top (required)>'
	from /Users/bolandross/.rbenv/versions/3.0.1/bin/pakyow:23:in `load'
	from /Users/bolandross/.rbenv/versions/3.0.1/bin/pakyow:23:in `<main>'
```

**Comment by bryanp** [comment]
Pakyow v1 doesn't and likely will not support Ruby 3. This is something being addressed in ongoing development in v2.
